# Generated by Django 5.1.6 on 2025-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_director_movieinfo_directed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='director',
            old_name='rating',
            new_name='name',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='acters',
            field=models.ManyToManyField(related_name='acted_movies', to='movies.actor'),
        ),
    ]
